### PR TITLE
DOC: Add page on CRUD operations with hydrus

### PR DESCRIPTION
**Pull request by sameshl**
* Lots of code in the docs was outdated. Updated them to the latest hydrus interface.
* Fixed typos

* Add a page describing how we could do all CRUD operations

### CODE REVIEW

**Comment by sameshl** [comment]
@chrizandr Sure. Will do.
But I wanted to know why do we have to two separate documentation? Are we considering moving the entire documentation to the readthedocs version?
That might also give us added benefits of versioning our docs.

**Comment by chrizandr** [comment]
Yes, we want to move all documentation to the readthedocs which should be built from files in hydrus itself. This should help in easier maintenance and updating the docs. Hopefully we will get this done in this year's season of docs.

**Comment by xadahiya** [comment]
Please resolve conflicts

**Comment by sameshl** [comment]
> Please resolve conflicts

Yes will resolve them once my work is complete. Should be done in some time

**Comment by sameshl** [comment]
@xadahiya Completed the work on using hydrus interface for performing CRUD operations. Also resolved the conflict.
Looks good to merge

**Pull request merged**
