### PR TITLE
Edited the Usage page

### PR DESCRIPTION
**Pull request by cindyhyl**
I fixed a couple simple grammatical and spelling errors. Mostly, I tried to reduce the amount of usage of "we" because this can make the instructions clearer. I also removed some words that are not needed from a couple of sentences. The overall goal of my edit was to make explanations as concise and as simple as possible. I hope this was helpful! Please let me know if I made any errors in my edits, and I'll fix them. 

Please approve the PR by Friday night. Thanks!

### CODE REVIEW

**Comment by cindyhyl** [comment]
Is there some way to separate my two edits into two PRs? Each PR counts as one point in my assignment so I'd like it to be separated into two. Thanks!

**Comment by ShravanDoda** [comment]
@cindyhyl you can create 2 different branches and push the changes from them

**Comment by cindyhyl** [comment]
Yea thanks, I'll do that!

**Comment by cindyhyl** [comment]
Alright, this should be good to go. This PR only has edits on the Usage page, and I created a second PR with edits on the Auth page.

**Pull request merged**
