### PR TITLE
Wrote starting doc about hydra-python-core library

### PR DESCRIPTION
**Pull request by de-sh**
Solves #54 

This is a starting doc mostly copied from the [relevant repo README](https://github.com/HTTP-APIs/hydra-python-core). 

Would love to hear opinions about how to better present same.

### CODE REVIEW

**Comment by Guttz** [comment]
I guess this is also useful, but what I had in mind with https://github.com/HTTP-APIs/http-apis.github.io/issues/54 was detailing how to use Core to interact with an apidoc. Ex.:

To initialize: 
`api_doc = doc_maker.create_doc(apidoc)`

To get a list of Supported Properties:
`api_doc.parsed_classes["DroneCollection"]["class"].supportedProperty`

To get a list Supported Operations:
`api_doc.collections[endpoint]["collection"].supportedOperation`

Along other basic actions which are useful when interacting with the apidoc. We currently have some different materials that cite doc_maker like Chris and Akshay's posts at
https://www.hydraecosystem.org/seasonofdocs-2019.

**Comment by de-sh** [comment]
Awesome, getting to it!

**Comment by xadahiya** [comment]
We probably want to main sections here. 
- A section explaining how the library can be used to write new a Hydra Vocab
- Another section explaining how the library can be used to interact with the APIDoc just like @Guttz  said.

**Comment by de-sh** [comment]
> We probably want to main sections here.
> 
> * A section explaining how the library can be used to write new a Hydra Vocab

Ok, so this will be more like in the tutorial sense, like how a make your own app article goes in most framework documentation.

**Comment by xadahiya** [comment]
Closing this. @de-sh Please make a PR once you've something substantial

**Pull request closed without merging**
